Update integretion workflow compatible with CML 2.5.1
ansible-network/github_actions pull request #145
Opened 2024-03-26 13:16 UTC by ashwini-mhatre

2024-03-27 06:49 UTC, NilashishC requested changes

2024-03-27 06:49 UTC, NilashishC commented on .github/workflows/integration.yml
> +          - stable-2.14
Can we bump this to stable-2.16? stable-2.14 is going to be EoL soon.

2024-03-27 12:05 UTC, abikouo requested changes

2024-03-27 12:05 UTC, abikouo commented on .github/actions/build_install_collection/action.yml
> +    default: "3.9"
This is a breaking change as it is supposed all workflows currently using this action should have `python3.9` installed in their environment

2024-03-27 12:05 UTC, abikouo commented on .github/actions/build_install_collection/action.yml
> +    - run: python${{ matrix.python-version }} -m pip install -r requirements.txt -r test-requirements.txt
you should also install `bindep` using the same python version (at line 53)

2024-03-28 11:24 UTC, NilashishC commented on .github/actions/build_install_collection/action.yml
> +    default: "3.9"
@abikouo Agreed. I think this option isn't even being used anywhere. We should just remove this?

2024-04-01 07:13 UTC, NilashishC approved these changes

2024-04-01 07:14 UTC, NilashishC requested changes

2024-04-01 07:14 UTC, NilashishC commented on .github/workflows/integration.yml
> +          python_version: ${{ matrix.python-version }}
We have removed this input, so this is no longer needed.

2024-04-01 13:07 UTC, ashwini-mhatre commented
@abikouo Addressed review comments .could you please have look?

2024-04-02 12:34 UTC, ashwini-mhatre commented
@GomathiselviS @cidrblock could you please have look to this PR?

2024-04-02 13:01 UTC, NilashishC commented on .github/actions/build_install_collection/action.yml
> +          python${{ matrix.python-version }} -m pip install bindep
Can't we use `python${{ matrix.python-version || '3' }}` here?

2024-04-03 07:05 UTC, NilashishC approved these changes

2024-04-03 07:13 UTC, merged