Support Depends-On
ansible-network/github_actions pull request #55
Opened 2023-03-24 14:57 UTC by abikouo

This github action allows to override the version of a collection to checkout based on keyword `depends-on` from pull request title
Extracted from #45

2023-03-24 14:58 UTC, abikouo commented
@Qalthos this one the feature extracted from #45
closes #49

2023-03-24 16:51 UTC, Qalthos requested changes

2023-03-24 16:51 UTC, Qalthos commented on .pre-commit-config.yaml
> +          - pygithub
You also need to add this to the mypy section to avoid Any

2023-03-24 16:51 UTC, Qalthos commented on .github/actions/checkout_repository/resolve_dependency.py
> +def get_pr_merge_commit_sha(repository: str, pr_number: int) -> Any:
```suggestion
def get_pr_merge_commit_sha(repository: str, pr_number: int) -> str:
```

2023-03-24 16:51 UTC, Qalthos commented on .github/actions/checkout_repository/resolve_dependency.py
> +    match = pr_regx.findall(pr_body)
This only handles the first `Depends-On` line. Is that expected to change? If not, why use findall here instead of search?

2023-03-24 16:51 UTC, Qalthos commented on .github/actions/checkout_repository/action.yml
Can you show how this is intended to be used? Is this supposed to replace regular checkout in the workflow files?

2023-03-27 14:26 UTC, abikouo commented on .github/actions/checkout_repository/resolve_dependency.py
> +    match = pr_regx.findall(pr_body)
Yes it should match only the first occurrence. PR has been updated with unit tests and README.md

2023-03-27 14:27 UTC, abikouo commented on .github/actions/checkout_repository/action.yml
yes, this has been described into README.md

2023-03-29 18:37 UTC, Qalthos requested changes
Okay, can you replace the `checkout` step

2023-03-29 19:34 UTC, Qalthos commented
Not with my fork, obviously, but can you update the existing workflows to switch to this instead of checkout? `changelog` and `safe-to-test` shouldn't need to be updated, but the rest would benefit from having it.

cf. https://github.com/Qalthos/github_actions/commit/8a31c25731258bd53bc6e7dd5b6d88912386b371

2023-03-30 06:07 UTC, abikouo commented on .github/actions/checkout_repository/action.yml
> +    required: true
The reason is to avoid having the repository being tested override, however, we can enforce it in the script
Let's say you are testing pull `request org/repo1/pull/1`, if you set `depends-on: org/repo1/pull/2` into the pull request body, therefore, using `checkout_repository` will test PR 2 instead of 1.

2023-03-30 10:30 UTC, abikouo commented
> Not with my fork, obviously, but can you update the existing workflows to switch to this instead of checkout? `changelog` and `safe-to-test` shouldn't need to be updated, but the rest would benefit from having it.
> 
> cf. [Qalthos@8a31c25](https://github.com/Qalthos/github_actions/commit/8a31c25731258bd53bc6e7dd5b6d88912386b371)

The only workflow which can benefit from this action is `integration.yml`, this action is used to checkout dependency only (It has been updated accordingly), this is why the `repository` parameter is required, we don't want to add `depends-on` in a repository being checkout

2023-03-31 14:42 UTC, Qalthos commented
> The only workflow which can benefit from this action is `integration.yml`, this action is used to checkout dependency only (It has been updated accordingly), this is why the `repository` parameter is required, we don't want to add `depends-on` in a repository being checkout

But this can absolutely be used to depends-on a PR that fixes sanity tests, for example. It's a contrived situation, but https://github.com/ansible-collections/ansible.utils/pull/248/checks?check_run_id=12373927044 and https://github.com/ansible-collections/ansible.utils/pull/248/checks are runs of the same checks with and without depends-on where another PR is fixing the underlying issue.

2023-03-31 14:49 UTC, Qalthos requested changes

2023-03-31 14:49 UTC, Qalthos commented on setup.cfg
This is all covered in [.flake8](https://github.com/ansible-network/github_actions/blob/main/.flake8), and I'm not sure why you're adding the D* checks to ignore.

2023-03-31 14:49 UTC, Qalthos commented on .gitignore
> +*__pycache__/
I'm _pretty_ sure this change is unnecessary, I can't think of anything that generates folders that end with __pycache__ but have something before that

2023-04-03 13:02 UTC, abikouo commented on setup.cfg
Removed

2023-04-03 13:03 UTC, abikouo commented on .gitignore
> +*__pycache__/
removed

2023-04-05 19:47 UTC, Qalthos approved these changes

2023-04-05 20:03 UTC, merged