ansible test splitter
ansible-network/github_actions pull request #63
Opened 2023-03-31 10:24 UTC by abikouo

For Ansible cloud collections the integration test job is supposed to test only targets impacted by the change to faster the execution. The script `list_changed_targets.py` is used to retrieve the list of theses targets

2023-03-31 11:02 UTC, cidrblock commented
Does the full test suite get run periodically?  Or as part of the release process? (just curious)

2023-03-31 11:05 UTC, abikouo commented
> Does the full test suite get run periodically? Or as part of the release process? (just curious)

for some collections it is periodically, but for all of them it is at least during the release process
note that you can add the label `test-all-the-targets` to run the full test suite

2023-03-31 11:19 UTC, cidrblock requested changes
good stuff........ The types and docs string make good looking code!

2023-03-31 11:19 UTC, cidrblock commented on .github/actions/ansible_test_splitter/list_changed_targets.py
> +    :Yields: python module import
`yields` vs `Yields` ?

2023-03-31 11:19 UTC, cidrblock commented on .github/actions/ansible_test_splitter/list_changed_targets.py
> +    def _parse_collection(element: str) -> tuple[PosixPath, str]:
Can this be pulled out to a global and documented?

2023-03-31 11:19 UTC, cidrblock commented on .github/actions/ansible_test_splitter/list_changed_targets.py
> +    collections_to_test, total_jobs, test_all_the_targets, targets_to_test = parse_inputs()
Can the code here be pulled into a func and called from here?  It will make it accessible from python if this script ever needs to be used programitcally, called a module, or invoked from another python process.  Maybe `main` for the func name

2023-04-04 13:49 UTC, cidrblock approved these changes

2023-04-12 14:14 UTC, merged